FROM python:3.8.13-slim
ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONUNBUFFERED 1

WORKDIR /app

COPY . /app/

RUN pip install --upgrade pip \
    && pip install -r requirements_manage.txt

EXPOSE 8000

CMD ["python", "plotly_analytics/manage.py", "runserver", "0.0.0.0:8000"]
