# Generated by Django 3.2.6 on 2024-08-20 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PersonalInfo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('bank_name', models.CharField(max_length=255)),
                ('person_name', models.CharField(max_length=255)),
                ('branch_name', models.CharField(max_length=255)),
                ('person_address', models.CharField(blank=True, max_length=255, null=True)),
                ('bank_address', models.CharField(blank=True, max_length=255, null=True)),
                ('account_no', models.CharField(max_length=20, unique=True)),
                ('ifsc', models.CharField(max_length=11)),
                ('customer_id', models.CharField(max_length=20, unique=True)),
            ],
            options={
                'db_table': 'Personal_Info',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TransactionInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_id', models.IntegerField()),
                ('bank_name', models.CharField(max_length=255)),
                ('person_name', models.CharField(max_length=255)),
                ('account_no', models.CharField(max_length=20)),
                ('transaction_date', models.DateField()),
                ('value_date', models.DateField()),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
                ('debit', models.DecimalField(decimal_places=2, default=0.0, max_digits=15)),
                ('credit', models.DecimalField(decimal_places=2, default=0.0, max_digits=15)),
                ('balance', models.DecimalField(decimal_places=2, default=0.0, max_digits=15)),
                ('label', models.CharField(blank=True, max_length=20, null=True)),
            ],
            options={
                'db_table': 'Transaction_Info',
                'managed': False,
            },
        ),
        migrations.DeleteModel(
            name='EmailsProcessed',
        ),
    ]
